### ISSUE TITLE
quesiton about the running code

### ISSUE THREAD

**Issue by opptimus** [XuanchenLi/Topo4D#5]
When I run "python train.py --input_dir test/videos_low --output_dir output --exp exp_op_dense --seq seq_01 --dense_input_dir test/videos --gen_tex --tex_res 8192" ,
there exit two bugs:
1.Unimplemented OBJ format statement 's' on line 's 0'
Unimplemented OBJ format statement 's' on line 's 0'
2.Traceback (most recent call last):
  File "/zdp/125_Topo4D/train.py", line 779, in <module>
    train(args)
  File "/mzz/125_Topo4D/train.py", line 647, in train
    dataset = get_dataset(args.input_dir, args.seq, t + 1, cameras, use_mask=use_mask, blacklist=blacklist)
  File "/mzz/125_Topo4D/train.py", line 98, in get_dataset
    cam = setup_camera(cam, w, h, k, w2c, near=0.01, far=100)
  File "/mzz/125_Topo4D/helpers.py", line 73, in setup_camera
    cam = Camera(
TypeError: GaussianRasterizationSettings.__new__() missing 1 required positional argument: 'debug'

Can you help me to cope with this problems?
Thanks very much!

**Comment by XuanchenLi** [comment]
Hi,  the message "Unimplemented OBJ format statement 's' on line 's 0'" is normal and does not affect anything. You can just ignore it.

Regarding the second bug you mentioned, it should be due to an inconsistent version of our diff-gaussian-rasterization. It can be seen that your version has an additional parameter called "debug". I think you can address this issue by setting debug=False in "/mzz/125_Topo4D/helpers.py", line 73. 
`cam = Camera(
        image_height=h,
        image_width=w,
        tanfovx=w / (2 * fx),
        tanfovy=h / (2 * fy),
        bg=torch.tensor([0, 0, 0], dtype=torch.float32, device="cuda"),
        scale_modifier=1.0,
        viewmatrix=w2c,
        projmatrix=full_proj,
        sh_degree=0,
        campos=cam_center,
        prefiltered=False,
        debug=False
    )`

**Comment by opptimus** [comment]
Thank you for your quick response. There's still one new error; I wonder if it's possible to fix it?
error:
1.timestep geometry 0:   0%|                                                         | 0/7000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/mzz/125_Topo4D/train.py", line 779, in <module>
    train(args)
  File "/mzz/125_Topo4D/train.py", line 658, in train
    loss, variables, loss_detail = get_loss(params, curr_data, variables, is_initial_timestep,
  File "/mzz/125_Topo4D/train.py", line 308, in get_loss
    im, radius, _, = Renderer(raster_settings=curr_data['cam'])(**rendervar)
ValueError: too many values to unpack (expected 3)
timestep geometry 0:   0%|                                                         | 0/7000 [00:02<?, ?it/s]

**Comment by XuanchenLi** [comment]
This issue is also due to the inconsistent version of the Gaussian renderer. You can check how many values are returned in the method "_ RasterizeGaussians. forward" in"diff_gaussian_rasterization/__init__. py". 

If you are using the latest version of [diff-gaussian-rasterization](https://github.com/ashawkey/diff-gaussian-rasterization/tree/main), you can try changing this line to `im, radius, _, _= Renderer(raster_settings=curr_data['cam'])(**rendervar)`

**Comment by opptimus** [comment]
Thank you for your patient reply, the problem has been resolved.
